# Generated by Django 4.1.2 on 2022-10-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='rollnumber',
            field=models.IntegerField(),
        ),
    ]
